### ISSUE TITLE
Switch and controller can not connect in SDN

### ISSUE THREAD

**Issue by Maitrey1992** [sdn-ixp/sdx#28]
root@mininet-vm:/home/mininet/pox# ./pox.py
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:core:POX 0.2.0 (carp) is up.

After this it shows nothing.can you suggest some idea

**Comment by agupta13** [comment]
Doesn't looks like an SDX issue. Re-start your controller and follow the instruction steps again.
